class variables

In [50]:
class Employee:

    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay

    def fullname(self):
        return '{} {}'.format(self.first, self.last)

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

in the above cell we define first, last and pay in the init method of the class but 
class variables are the variables that are shared among all instances of a class. but instane variables are unique to each instance example: first_name, last_name and pay

and class variable is same for each instance.

from above example, what kind of data that can be shared among all employees? 
ans: that can be "pay"

let us assume that company is giving annual raise to all employees and whatever it gives will be same for  all the employees. ex: 4 percent.

In [65]:
#why class variables ? 
class Employee:

    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * 1.04)

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

print(emp_1.pay)
emp_1.apply_raise()
print(emp_1.pay)



50000
52000


In [66]:
#how to access the raise amount
class Employee:

    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * 1.04)

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

print(emp_1.pay)
emp_1.apply_raise()
print(emp_1.pay)

#raise amount
emp_1.raise_amount
emp_2.raise_amount


50000
52000


AttributeError: 'Employee' object has no attribute 'raise_amount'

In [67]:
#how to access the raise amount
class Employee:
    raise_amount = 1.04
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * raise_amount)

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

print(emp_1.pay)
emp_1.apply_raise()
print(emp_1.pay)

# error is because we can access the class variables through class itself or an instance of class

50000


NameError: name 'raise_amount' is not defined

In [68]:
#how to access the raise amount
class Employee:
    raise_amount = 1.04
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * Employee.raise_amount) # access through class name itself

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

print(emp_1.pay)
emp_1.apply_raise()
print(emp_1.pay)

50000
52000


In [55]:
#how to access the raise amount
class Employee:
    raise_amount = 1.04
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * self.raise_amount) #access through instance of the class

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

print(emp_1.pay)
emp_1.apply_raise()
print(emp_1.pay)

50000
52000


In [56]:
#how to access the raise amount
class Employee:
    raise_amount = 1.04 #class variable
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * raise_amount)

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

print(Employee.raise_amount) #accessing class variable by class name
print(emp_1.raise_amount) #accessing class variable by instance
print(emp_2.raise_amount) #accessing class variable by instance


1.04
1.04
1.04


In [57]:
#accessing the raise amount using class name and instance 
class Employee:
    raise_amount = 1.04 #class variable
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * raise_amount)

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

print(Employee.raise_amount) #accessing class variable by class name
print(emp_1.raise_amount) #accessing class variable by instance
print(emp_2.raise_amount) #accessing class variable by instance


1.04
1.04
1.04


In the above cell, when we access class variable using Employee.raise_amount we got output = 1.04 which is obvious

but when we try to access an attribute from an instance, it first looks whether instance contains that attribute and executes with that value of 'raise_amount'.
"but here instance ('emp_1') doesn't have any such attribute. So it looks into class, whether that attribute is in the class, that it inherits from and if present then takes that value."

In [58]:
#accessing the raise amount using class name and instance 
class Employee:
    raise_amount = 1.04 #class variable
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * raise_amount)

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

print(emp_1.__dict__)  #extracting the key and values of the instance
print(emp_2.__dict__) #extracting the key and values of the instance

{'first': 'Corey', 'last': 'Schafer', 'email': 'Corey.Schafer@email.com', 'pay': 50000}
{'first': 'Test', 'last': 'Employee', 'email': 'Test.Employee@email.com', 'pay': 60000}


In the above output we are not getting raise_amount attribute in the instances of the class

In [59]:
#accessing the raise amount using class name and instance 
class Employee:
    raise_amount = 1.04 #class variable
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * self.raise_amount)

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

print(Employee.__dict__)

{'__module__': '__main__', 'raise_amount': 1.04, '__init__': <function Employee.__init__ at 0x0000000008015798>, 'fullname': <function Employee.fullname at 0x0000000008015EE8>, 'apply_raise': <function Employee.apply_raise at 0x0000000008015318>, '__dict__': <attribute '__dict__' of 'Employee' objects>, '__weakref__': <attribute '__weakref__' of 'Employee' objects>, '__doc__': None}


in the above cell class does contain attribute 'raise_amount' and this the value that the instance accesses from the class variable.

In [60]:
#accessing the raise amount using class name and instance 
class Employee:
    raise_amount = 1.04 #class variable
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * self.raise_amount)

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

Employee.raise_amount = 1.05

print(Employee.raise_amount)
print(emp_1.raise_amount) 
print(emp_2.raise_amount)

1.05
1.05
1.05


in the above cell raise amount is changed to 1.05 and the value is changed to all the instance and class variable

In [61]:
#accessing the raise amount using class name and instance 
class Employee:
    raise_amount = 1.04 #class variable
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * self.raise_amount)

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

emp_1.raise_amount = 1.05

print(emp_1.__dict__)

print(Employee.raise_amount)
print(emp_1.raise_amount) 
print(emp_2.raise_amount)

{'first': 'Corey', 'last': 'Schafer', 'email': 'Corey.Schafer@email.com', 'pay': 50000, 'raise_amount': 1.05}
1.04
1.05
1.04


here in above cell the attribute raise amount is changed only for emp_1 . and the 
remaining instance like emp_2 and class variable take the same class variable value. And this is because when instance emp_1 looks into its attributes, it finds the attribute "raise_amount" in it. But in the instance emp_2 doesn't have the attribute raise_amount in it, so it takes the value from the class variable = 1.04 in this case.

In [62]:
# where does not add meaning to add self (no of employees case)
class Employee:
    raise_amount = 1.04 #class variable
    no_of_employees = 0
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
        
        Employee.no_of_employees +=1
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * self.raise_amount)

print(Employee.no_of_employees)        

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

emp_1.raise_amount = 1.05

print(Employee.no_of_employees)

0
2


In [63]:
# where does not add meaning to add self (no of employees case)
class Employee:
    raise_amount = 1.04 #class variable
    no_of_employees = 0
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
        
        self.no_of_employees +=1
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * self.raise_amount)

print(Employee.no_of_employees)        

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

emp_1.raise_amount = 1.05

print(Employee.no_of_employees)

0
0


In [73]:
# where does not add meaning to add self (no of employees case)
class Employee:
    raise_amount = 1.04 #class variable
    no_of_employees = 0
    
    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay
        
    
    def fullname(self):
        return '{} {}'.format(self.first, self.last)
   
    def apply_raise(self):
        self.pay = int(self.pay * self.raise_amount)
        self.no_of_employees +=1
        
    def cnt_empl(self):
        self.no_of_employees += 1
        
print(Employee.no_of_employees)        

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

emp_1.raise_amount = 1.05

print(apply_raise(no_of_employees))

0


NameError: name 'apply_raise' is not defined